### ISSUE TITLE
IM crashes when loading messages

### ISSUE THREAD

**Issue by BeniyashaSSB** [CakeKing64/P5IM-android-10-fix#7]
Hi, I just found this and installed it, and it looks super cool! I wish I could use it, but whenever I load any messages, it says an error has occurred, and prompts a box that asks for what happened and an email to contact me with. This happens whether or not I select a message chain that has mms messages in it. I can send further details if you need it

**Comment by CakeKing64** [comment]
If you want to send some more details do, though it might be a problem I can't fix (I don't have the actual source code so can't change anything major at all)
I'll still take a look though

**Comment by BeniyashaSSB** [comment]
Alright, so basically, I'm on an LG G8 ThinQ, and every time I select a message chain, an error box asking for that stuff opens. Image below showing what the box looks like.
I was under the assumption that this only applied to mms messages, but it also applies to message chains where there were no mms at all. I even fiddled with the app's built in settings, but that didn't change it.
I'm sorry, I thought I would be able to share more details, but I guess not, huh?

![Screenshot_20211223-195154](https://user-images.githubusercontent.com/87156921/147303156-3d556a2e-e3c2-4639-be0c-b846e769ba9d.png)

**Comment by CakeKing64** [comment]
My guess it's an error that I probably can't fix as I can't find anything in the app manifest that might be the cause, but if you really want to at least confirm it i can write down the steps for using ADB to determine the crash (sorry about the long wait to me saying anything useful ratio lmao)

**Comment by BeniyashaSSB** [comment]
I recently got a Samsung galaxy s21, and it no longer crashes when opening a recipient. I'm sorry for the extremely long delay in responding.
